name: F7forTOP50influencerwomen
favicon: null
layout_spectrum: 0.5965248721186072
typography_spectrum: 0.23465802683494985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8974457725416869
  lightness: 0.010141640668734908
  saturation: 0.9239183054305613
  rhythmicContrast: 0.9994589881971478
purpose: []
