name: félhét és az 50 legbefolyásosabb magyar nő
favicon: null
layout_spectrum: 0.59412
typography_spectrum: 0.52244
title: félhét és az 50 legbefolyásosabb magyar nő
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d92227'
    - '#fefefc'
    - '#fac2c0'
    - '#ca5659'
    - '#df9c9a'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
